## template: jinja
#cloud-config
package_update: true
packages:
  - nginx
write_files:
  - path: /etc/nginx/nginx.conf
    content: |
      worker_processes auto;
      worker_rlimit_nofile 8192;

      events {
        worker_connections  1024;  ## Default: 1024
      }

      http {
        server {
          location / {
            root /data/www;
          }
        }
      }
  - path: /data/www/index.html
    content: |
      <!DOCTYPE html>
      <html>
          <head>
              <title>Azure-Learning</title>
          </head>
          <body>
              <p>{{ v1.instance_id }}</p>
          </body>
      </html>
runcmd:
  - cat /data/www/index.html
  - echo '{{ v1.instance_id }}'
  - systemctl restart nginx